modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/imod/issues"

[[mods]]
modId="imod"
version="1.4.3"
displayName="iMOD"
updateJSONURL="https://gist.githubusercontent.com/VikkiVuk/91b9c1960ec92b4e7ead408cc6582556/raw"
displayURL="https://www.youtube.com/VikkiVuk"
logoFile="minecraft w imod green.png"
credits="All credits for this mod go to me"
authors="VikkiVuk"
description='''
Hey guys, i just wanna say that my first mod named HystelMC has almost 1k downloads, so if we could get it to 1k downloads that would be amazing!
Because of certain circumstances i've been unable to work on this mod for a long time, its complicated, anyways i will try my best to work on this mod.
If you have any suggestions please go look on the curseforge mod page theres a suggest feature picture there!
Keep your heads up, Stay safe!
'''

[[dependencies.imod]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.imod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.imod]]
modId="icore"
mandatory=true
versionRange="[1.4.1]"#
ordering="NONE"
side="BOTH"
